services:
  affine:
    image: ghcr.io/toeverything/affine:stable@sha256:d9d145f9f47b862d1fa96e2a887052b5762846237f75fbb077be990ef646e05c
    container_name: affine
    restart: unless-stopped
    depends_on:
      affine_redis:
        condition: service_healthy
      affine_postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    environment:
      - REDIS_SERVER_HOST=affine_redis
      - DATABASE_URL=postgresql://affine:${AFFINE_DB_PASSWORD}@affine_postgres:5432/affine
      - AFFINE_SERVER_EXTERNAL_URL=https://affine.okryshto.dev
      - AFFINE_INDEXER_ENABLED=false
    volumes:
      - affine_config:/root/.affine/config
      - affine_storage:/root/.affine/storage

  affine_migration:
    image: ghcr.io/toeverything/affine:stable@sha256:d9d145f9f47b862d1fa96e2a887052b5762846237f75fbb077be990ef646e05c
    container_name: affine_migration
    depends_on:
      affine_redis:
        condition: service_healthy
      affine_postgres:
        condition: service_healthy
    volumes:
      - affine_config:/root/.affine/config
      - affine_storage:/root/.affine/storage
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      - REDIS_SERVER_HOST=affine_redis
      - DATABASE_URL=postgresql://affine:${AFFINE_DB_PASSWORD}@affine_postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false

  affine_postgres:
    image: postgres:16
    container_name: affine_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=affine
      - POSTGRES_PASSWORD=${AFFINE_DB_PASSWORD}
      - POSTGRES_DB=affine
    volumes:
      - affine_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U affine"]
      interval: 5s
      timeout: 5s
      retries: 10

  affine_redis:
    image: redis:7-alpine
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - affine_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  affine_config:
  affine_storage:
  affine_postgres_data:
  affine_redis_data:
